"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-22 00:09:41.173935
"""
import sqlalchemy as sa
from alembic import op

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adaptation_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('strategy', sa.String(length=40), nullable=True),
    sa.Column('event', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('adaptation_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adaptation_job_job_id'), ['job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_adaptation_job_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adaptation_job_status'), ['status'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_job_id'), ['job_id'], unique=False)

    op.create_table('dataset_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_metadata_dataset_id'), ['dataset_id'], unique=True)

    op.create_table('model_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('mlflow_model_name', sa.String(length=200), nullable=False),
    sa.Column('model_type', sa.String(length=100), nullable=True),
    sa.Column('framework', sa.String(length=50), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('target_column', sa.String(length=200), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_metadata_model_id'), ['model_id'], unique=True)

    op.create_table('adaptation_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['adaptation_job.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adaptation_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adaptation_event_job_id'), ['job_id'], unique=False)

    op.create_table('data_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('data_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_metadata.id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['data_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'version')
    )
    with op.batch_alter_table('data_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_version_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('data_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_version_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['data_version_id'], ['data_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_record_data_version_id'), ['data_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_record_observed_at'), ['observed_at'], unique=False)

    op.create_table('model_data_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('data_version_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_version_id'], ['data_version.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model_metadata.model_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'model_version', 'data_version_id', 'role')
    )
    with op.batch_alter_table('model_data_association', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_data_association_model_id'), ['model_id'], unique=False)

    op.create_table('performance_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('data_version_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_version_id'], ['data_version.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model_metadata.model_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_record_model_id'), ['model_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_record_model_id'))

    op.drop_table('performance_record')
    with op.batch_alter_table('model_data_association', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_data_association_model_id'))

    op.drop_table('model_data_association')
    with op.batch_alter_table('data_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_record_observed_at'))
        batch_op.drop_index(batch_op.f('ix_data_record_data_version_id'))

    op.drop_table('data_record')
    with op.batch_alter_table('data_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_version_dataset_id'))

    op.drop_table('data_version')
    with op.batch_alter_table('adaptation_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adaptation_event_job_id'))

    op.drop_table('adaptation_event')
    with op.batch_alter_table('model_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_metadata_model_id'))

    op.drop_table('model_metadata')
    with op.batch_alter_table('dataset_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_metadata_dataset_id'))

    op.drop_table('dataset_metadata')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_job_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('adaptation_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adaptation_job_status'))
        batch_op.drop_index(batch_op.f('ix_adaptation_job_model_id'))
        batch_op.drop_index(batch_op.f('ix_adaptation_job_job_id'))

    op.drop_table('adaptation_job')
    # ### end Alembic commands ###
