"""Shared enumerations for the adaptation pipeline."""

from enum import StrEnum


class JobStatus(StrEnum):
    RECEIVED = "RECEIVED"
    ANALYZING = "ANALYZING"
    MODEL_COMPARISON = "MODEL_COMPARISON"
    DECISION_PENDING = "DECISION_PENDING"
    DECISION_MADE = "DECISION_MADE"
    ADAPTING = "ADAPTING"
    VALIDATING = "VALIDATING"
    REGISTERING = "REGISTERING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ROLLED_BACK = "ROLLED_BACK"


TERMINAL_STATUSES = frozenset({JobStatus.COMPLETED, JobStatus.FAILED, JobStatus.ROLLED_BACK})


class Strategy(StrEnum):
    FINE_TUNING = "FINE_TUNING"
    FULL_RETRAINING = "FULL_RETRAINING"
    ROLLBACK = "ROLLBACK"
    NO_ACTION = "NO_ACTION"
    INSUFFICIENT_INFORMATION = "INSUFFICIENT_INFORMATION"
    NO_COMPATIBLE_STRATEGY = "NO_COMPATIBLE_STRATEGY"


class DataKind(StrEnum):
    HISTORICAL = "HISTORICAL"
    DRIFTED = "DRIFTED"


class AssociationRole(StrEnum):
    TRAINING = "TRAINING"
    VALIDATION = "VALIDATION"
    DRIFT_OBSERVED = "DRIFT_OBSERVED"


class EngineKind(StrEnum):
    SKLEARN_PARTIAL_FIT = "SKLEARN_PARTIAL_FIT"
    SKLEARN_FULL_RETRAIN = "SKLEARN_FULL_RETRAIN"
    XGBOOST_FULL_RETRAIN = "XGBOOST_FULL_RETRAIN"
    TORCH_FINE_TUNE = "TORCH_FINE_TUNE"
    TORCH_FULL_RETRAIN = "TORCH_FULL_RETRAIN"
    LLM_GENERATED = "LLM_GENERATED"
