"""Regenerate docs/security/authz-matrix.md: every API route, the actions its policy requires, and
which roles the default POLICY_ROLES lets through. The table is built from the routes the app
actually serves (oran_adapt.api.security.authz_matrix_markdown), so it cannot drift from the
code; test_phase9_security fails when this file is stale.

Usage:  python scripts/authz_matrix.py
"""

from __future__ import annotations

import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "security" / "authz-matrix.md"

HEADER = """# Authorization matrix

Generated by `python scripts/authz_matrix.py` from the routes the API serves and the default
`POLICY_ROLES`; `tests/unit/test_phase9_security.py` fails when it is stale. Deny by default:
a route that declares no policy stops the API from starting, and an action missing from
`POLICY_ROLES` is allowed to nobody. With `AUTH_ENABLED=false` (local development only) every
caller is an ADMIN. Change who may do what with `POLICY_ROLES`, not here.

`yes` = the role may call the route; `-` = 403. Callers with no valid credential get 401 on
every route that is not `public`. `/metrics` is public while `METRICS_PUBLIC` is true.

"""


def main() -> int:
    sys.path.insert(0, str(ROOT / "src"))
    from oran_adapt.api.app import create_app
    from oran_adapt.api.security import authz_matrix_markdown
    from oran_adapt.core.config import Settings

    # ignore_cleanup_errors: on Windows the MLflow SQLite file can stay locked until exit.
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as tmp:
        settings = Settings(
            _env_file=None,
            database_url=f"sqlite:///{Path(tmp, 'app.db').as_posix()}",
            mlflow_tracking_uri=f"sqlite:///{Path(tmp, 'mlflow.db').as_posix()}",
            artifact_workdir=str(Path(tmp, "work")),
            notification_dispatch_enabled=False,
            api_docs_enabled=False,
        )
        table = authz_matrix_markdown(create_app(settings), settings.policy_roles)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(HEADER + table, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT).as_posix()} ({table.count(chr(10)) - 2} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
