"""Regenerate docs/capability-matrix.md from the adapters' own Capability descriptors.

Every first-party adapter (the ``oran_adapt.<port>`` entry points in pyproject.toml) is loaded
through ``oran_adapt.plugins`` and described by what it declares: its features, the keys it
reads and requires, and the optional packages it needs. Third-party plugins installed in the
environment are left out, so the file is the same on every machine.

Usage:
    python scripts/capability_matrix.py           # rewrite the file
    python scripts/capability_matrix.py --check   # exit 1 if the file is stale
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "capability-matrix.md"
GROUP_PREFIX = "oran_adapt."

HEADER = """# Capability matrix

Generated by `python scripts/capability_matrix.py` from each adapter's `Capability` descriptor
(`oran_adapt.ports.capability`); `scripts/acceptance/phase14.py` fails when it is stale. Do not
edit by hand: change the adapter's descriptor and regenerate.

- **Selected by**: the setting that picks the adapter (`-`: built by another adapter or listed
  in `MODEL_TYPES`). **Default**: that setting's default value.
- **Required keys** must be set when the adapter is selected; startup and `oran-adapt config
  lint` fail naming them. **Production keys** default to a local path and must be set
  explicitly under `ENVIRONMENT=production`.
- **Packages**: the optional distributions the adapter imports (`pip install` the extra named
  in `pyproject.toml`).

"""


def first_party() -> dict[str, list[str]]:
    """Port -> adapter names this project's pyproject.toml registers."""
    with (ROOT / "pyproject.toml").open("rb") as fh:
        groups = tomllib.load(fh)["project"]["entry-points"]
    return {group.removeprefix(GROUP_PREFIX): sorted(eps)
            for group, eps in groups.items() if group.startswith(GROUP_PREFIX)}


def _cell(values: list[str] | tuple[str, ...] | frozenset[str]) -> str:
    return ", ".join(f"`{v}`" for v in sorted(values)) or "-"


def render() -> str:
    sys.path.insert(0, str(ROOT / "src"))
    from oran_adapt import plugins
    from oran_adapt.core.config import ADAPTER_SELECTORS, Settings
    from oran_adapt.ports import PORTS

    selector_of = {port: key for key, port in ADAPTER_SELECTORS.items()}
    ours = first_party()
    lines = [HEADER.rstrip("\n") + "\n", "## Ports\n", "| Port | Selected by | Default | Adapters |",
             "|---|---|---|---|"]
    for port in PORTS:
        key = selector_of.get(port)
        default = Settings.model_fields[key].default if key else None
        names = ours.get(port, [])
        lines.append(f"| [`{port}`](#{port.replace('_', '-')}) | "
                     f"{f'`{key.upper()}`' if key else '-'} | "
                     f"{f'`{default}`' if default is not None else '-'} | "
                     f"{', '.join(f'`{n}`' for n in names) or '-'} |")
    for port in PORTS:
        installed = plugins.adapters(port)
        names = [n for n in ours.get(port, []) if n in installed]
        lines += ["", f"## {port.replace('_', '-')}", ""]
        if not names:
            lines.append("No first-party adapter; install a plugin (docs/adapter-authoring.md).")
            continue
        lines += [("| Adapter | Features | Required keys | Production keys | Packages | "
                   "Description |"), "|---|---|---|---|---|---|"]
        for name in names:
            cap = installed[name].capability
            description = " ".join(cap.description.split()).replace("|", "\\|")
            lines.append(
                f"| `{name}` | {_cell(cap.features)} | "
                f"{_cell([k.upper() for k in cap.required_keys])} | "
                f"{_cell([k.upper() for k in cap.production_keys])} | "
                f"{_cell(cap.distributions)} | {description} |"
            )
        features = sorted({f for n in names for f in installed[n].capability.features})
        if len(names) > 1 and features:
            lines += ["", "| Feature | " + " | ".join(f"`{n}`" for n in names) + " |",
                      "|---|" + "---|" * len(names)]
            for feature in features:
                marks = ["yes" if feature in installed[n].capability.features else "-"
                         for n in names]
                lines.append(f"| `{feature}` | " + " | ".join(marks) + " |")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args(argv)
    text = render()
    rel = OUT.relative_to(ROOT).as_posix()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{rel} is stale: run python scripts/capability_matrix.py")
            return 1
        print(f"{rel} is up to date")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
