"""Write requirements.lock: the exact versions of oran-adapt's runtime dependencies (and their
dependencies) as installed in the current environment.

Only the runtime closure is locked - not pytest, ruff or other dev tools. A dependency that is
only ever required under a platform marker (e.g. pywin32 on Windows) keeps that marker, so the
lock installs on Linux (the Docker image) as well as on the Windows dev machine.

Usage:  python scripts/lock_requirements.py [--extra kafka] [--output requirements.lock]
"""

from __future__ import annotations

import argparse
import re
import tomllib
from importlib import metadata
from pathlib import Path

from packaging.markers import default_environment
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

_PLATFORM = re.compile(r"sys_platform|platform_system|os_name|platform_machine")


def _project_requirements(pyproject: Path, extras: list[str]) -> list[str]:
    """The project's own requirements, read from pyproject.toml - not from the installed
    metadata, which is stale until the project is reinstalled."""
    project = tomllib.loads(pyproject.read_text(encoding="utf-8"))["project"]
    specs = list(project.get("dependencies", []))
    for extra in extras:
        specs += project.get("optional-dependencies", {}).get(extra, [])
    return specs


def _closure(root_specs: list[str]) -> dict[str, list[str | None]]:
    """Map each reachable distribution to the markers of the edges that reached it (None = an
    edge without a platform marker)."""
    env = default_environment()
    seen: dict[str, list[str | None]] = {}
    todo: list[tuple[str | None, set[str]]] = [(None, set())]
    done: set[tuple[str, frozenset[str]]] = set()
    while todo:
        name, want = todo.pop()
        if name is None:
            specs = root_specs
        else:
            key = (canonicalize_name(name), frozenset(want))
            if key in done:
                continue
            done.add(key)
            try:
                specs = metadata.distribution(name).requires or []
            except metadata.PackageNotFoundError:
                continue  # an optional dependency that is not installed here
        for spec in specs:
            req = Requirement(spec)
            marker = str(req.marker) if req.marker else ""
            # Evaluate everything except the platform part against this environment, per extra.
            ok = False
            for extra in want or {""}:
                ctx = {**env, "extra": extra}
                if req.marker is None or req.marker.evaluate(ctx):
                    ok = True
                elif _PLATFORM.search(marker) and "extra" not in marker:
                    ok = True  # needed on another platform: keep it, with its marker
            if not ok:
                continue
            platform_marker = marker if _PLATFORM.search(marker) else None
            seen.setdefault(canonicalize_name(req.name), []).append(platform_marker)
            todo.append((req.name, set(req.extras)))
    return seen


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pyproject", default="pyproject.toml")
    parser.add_argument("--extra", action="append", default=[])
    parser.add_argument("--output", default="requirements.lock")
    args = parser.parse_args()

    lines = []
    for name, markers in sorted(
        _closure(_project_requirements(Path(args.pyproject), args.extra)).items()
    ):
        try:
            version = metadata.version(name)
        except metadata.PackageNotFoundError:
            continue  # required only on another platform and not installed here: cannot pin
        # A platform marker is kept only when every edge that reached the package had one.
        marker = markers[0] if all(m is not None for m in markers) else None
        lines.append(f"{name}=={version}" + (f" ; {marker}" if marker else ""))

    header = (
        "# Generated by scripts/lock_requirements.py from the installed environment - do not edit.\n"
        f"# Runtime dependencies of {args.pyproject}"
        + (f" (extras: {', '.join(args.extra)})" if args.extra else "")
        + ".\n"
    )
    Path(args.output).write_text(header + "\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(lines)} pins to {args.output}")


if __name__ == "__main__":
    main()
